### ISSUE TITLE
[Feature] Add Food & Drinks

### ISSUE THREAD

**Issue by ortegamarcel** [ortegamarcel/fvtt-token-action-hud-thewitchertrpg#18]
I am not sure about this one and want to get some feedback.

I have some players who are roleplaying "enough" that they eat and drink regularly. For that it might become handy to have a action for it. But I am not sure if it would be really used that often. Sure that one would be also important for Players and not the GM.

It should definitely by possible to disable it in the settings.

**Comment by RKMkovi** [comment]
My players would love a feature like that. I houserule that they need to eat and drink regularly to prevent penalties from exhaustion and having a quick way to consume the food and drinks form the inventory would be amazing.
