### ISSUE TITLE
[Bug] Stealth is configured as Athletics

### ISSUE THREAD

**Issue by LinkDragmire** [ortegamarcel/fvtt-token-action-hud-thewitchertrpg#23]
While checking which skills I want configured as active, I recognized that there are 2 Athletic buttons ins the HUD. When rolling, the second one is stated as stealth.

Line 100 in the constants.js must be corrected to:

        stealth: { stat: 'dex', active: true, name: 'WITCHER.SkDexStealth', statNum: 2, skillNum: 4 },

This should solve this bug.

**Comment by ortegamarcel** [comment]
Thanks, nice find. I will fix it in the next release.
