### ISSUE TITLE
V11 Compatibility

### ISSUE THREAD

**Issue by Araluen124** [ortegamarcel/fvtt-token-action-hud-thewitchertrpg#38]
Hi, just wondering if the alpha version of The witcher will be updated to v11

**Comment by ortegamarcel** [comment]
hi. I am not 100% sure, what you mean with alpha version? Is there a problem with this module, "Token Action HUD"? I will check everything on v11, and do an update if something is broken.

**Comment by Araluen124** [comment]
I mean the version of the Witcher System that you made for this module (Because V11 blocks you from even opening systems not compatible)

**Comment by ortegamarcel** [comment]
Oh okay, thanks for the info. I will check that ASAP.

**Comment by ortegamarcel** [comment]
Released new Version of the Alpha Witcher TRPG, `0.97-alpha.5`. Now supports Foundry v11 (Build 305).

**Comment by ortegamarcel** [comment]
I also checked that Token Action HUD TheWitcherTRPG works fine with version 11 and updated the official foundry module. I already released version 1.1.0 of this module but forgot to update the official module as well. If you now install it by searching for the module it should show the newest version and say, that it is fully compatible (with version Foundry 11.305).

**Comment by Davrill** [comment]
Hi there - thank you loads for your work on this, and supporting this system. I can't see anywhere to log issues over your alpha version, but it seems that the Actor -> Item sheet no longer allows you to open Valuables or Diagrams, or add them to it?

**Comment by ortegamarcel** [comment]
I activated the issues tab on the Witcher Alpha project. So now you can report issues there. I already create one for your reported bug. https://github.com/ortegamarcel/TheWitcherTRPG/issues/13
