### ISSUE TITLE
Action HUD - Core Update

### ISSUE THREAD

**Issue by Siryphas** [ortegamarcel/fvtt-token-action-hud-thewitchertrpg#41]
Hello,
When I try to use this module, I keep getting a red bar error at the top saying that I need to use Token Action HUD Core 1.4 in order to use it. However, the Core module is now at v1.5.2. Is there any chance this can be updated to function with the newer Core update?

**Comment by ortegamarcel** [comment]
Update to version 1.1.2. It should solve all issues related to "wrong" version of Token Action HUD Core. Please confirm, once you tested it, so I can close the issue.

**Comment by Siryphas** [comment]
I'm on Version 1.5.2, you want me to go back to version 1.1.2?

**Comment by Stexinator** [comment]
I installed it in my world and aint got errors. So I think it is working

**Comment by Stexinator** [comment]
Core is now at 1.5.4 so that happens again

**Comment by ortegamarcel** [comment]
With the next release it will be compatible with the foundry v12 and also all newest module versions including Token Action HUD Core. (See [Issue 46 - v12 compatibility](https://github.com/ortegamarcel/fvtt-token-action-hud-thewitchertrpg/issues/46))
