### ISSUE TITLE
v12 compatibility

### ISSUE THREAD

**Issue by Stexinator** [ortegamarcel/fvtt-token-action-hud-thewitchertrpg#46]
Are there already plans for v12 compatibility?

https://github.com/Larkinabout/fvtt-token-action-hud-core/blob/main/module.json seems to be v12 compatible now

**Comment by Stexinator** [comment]
I checked it on my local dev environment and I didnt get any red errors

**Comment by ortegamarcel** [comment]
I have more time now and plan to fix the whole module for Foundry v12, ASAP.

**Comment by ortegamarcel** [comment]
There is a new release that is fully compatible with Foundry v12 and my [Witcher System fork v1.0.0](https://github.com/ortegamarcel/TheWitcherTRPG/releases/tag/v1.0.0)
