### ISSUE TITLE
Nothing Showing Up In Combat>Attack

### ISSUE THREAD

**Issue by AlexanderTheGr3at** [ortegamarcel/fvtt-token-action-hud-thewitchertrpg#47]
What the title says. There is nothing in the attack section. 

![Attack](https://github.com/ortegamarcel/fvtt-token-action-hud-thewitchertrpg/assets/59134326/38283dbd-eedf-4b83-8fbb-ee99534d396a)
![Attack 2](https://github.com/ortegamarcel/fvtt-token-action-hud-thewitchertrpg/assets/59134326/bd6d3b8e-c3d6-4cc2-b67a-23a3e1246a96)

**Comment by ortegamarcel** [comment]
I have more time now and plan to fix the whole module for Foundry v12, including this bug, ASAP.

**Comment by ortegamarcel** [comment]
I released a new version of this module and my [Witcher System Fork](https://github.com/ortegamarcel/TheWitcherTRPG/releases/tag/v1.0.0). They are now again fully compatible with each other.

I am also working together with Stexinator to make it compatible with his fork.
