### ISSUE TITLE
Skill rolls do not work.

### ISSUE THREAD

**Issue by Melkkart** [ortegamarcel/fvtt-token-action-hud-thewitchertrpg#6]
Skill rolls do not work.
Combat skills work correctly, but ability skills do not.

If you don't mind, could you add Magic? 
and I personally want to thank you for your work.

**Comment by ortegamarcel** [comment]
Please take a look at the [Known Issues](https://github.com/ortegamarcel/fvtt-token-action-hud-thewitchertrpg#known-issues) about how to fix the skills.

Magic will come with the next version.

**Comment by Melkkart** [comment]
ok I found this ...
![fail](https://user-images.githubusercontent.com/123239719/236675617-59cce367-fb93-47ba-b393-cf9b232c4475.jpg)

I use v0.97-alpha.3
I will try, xDDD

**Comment by Melkkart** [comment]
Ok, fix, thks @ortegamarcel
